version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - python3-gdal

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - doc
